### ISSUE TITLE
Module not found in version 1.1.1

### ISSUE THREAD

**Issue by YouHusam** [hapijs/catbox-mongodb#18]
Hi, for some reason I'm getting  ```Error: Cannot find module 'catbox-mongodb'``` in version 1.1.1, everything works normally in version 1.1.0 

I'm using node 4.1.1 and npm 3.3.6 

I tried ```require('node_modules/catbox-mongodb/lib')``` and it worked.

here's my output
```
> require('catbox-mongodb')
Error: Cannot find module 'catbox-mongodb'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at repl:1:1
    at REPLServer.defaultEval (repl.js:164:27)
    at bound (domain.js:250:14)
    at REPLServer.runBound [as eval] (domain.js:263:12)
    at REPLServer.<anonymous> (repl.js:393:12)
    at emitOne (events.js:82:20)
> require('./node_modules/catbox-mongodb/lib')
{ [Error: Cannot find module '../build/Release/bson'] code: 'MODULE_NOT_FOUND' }
js-bson: Failed to load c++ bson extension, using pure JS version
[Function]
```
Thank you

**Comment by lloydbenson** [comment]
Can you see if this change fixes it?

**Comment by YouHusam** [comment]
Yes it does

**Comment by jardakotesovec** [comment]
@YouHusam 1.1.2 published with @lloydbenson fix
